name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: '1.5.1'

    - name: Install dependencies
      run: poetry install

    - name: Check Poetry lock file
      run: poetry lock --check

    - name: Run Ruff
      run: |
        pip install ruff
        ruff check --fix .

    - name: Run Black
      run: |
        pip install black
        black --check .

    - name: Run isort
      run: |
        pip install isort
        isort --check-only --diff .

    - name: Run tests
      run: |
        poetry run pytest
